apiVersion: v1
kind: Secret
metadata:
  name: {{ template "miles-challenge.fullname" . }}
  labels:
    app: {{ template "miles-challenge.name" . }}
    chart: {{ template "miles-challenge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SLACK_CHANNEL_HOOK_URL: {{ .Values.secret.SLACK_CHANNEL_HOOK_URL |b64enc }}
  STRAVA_API_CLIENT_ID: {{ .Values.secret.STRAVA_API_CLIENT_ID |b64enc }}
  STRAVA_API_CLIENT_SECRET: {{ .Values.secret.STRAVA_API_CLIENT_SECRET |b64enc }}
  STRAVA_TOKEN_ENDPOINT: {{ .Values.secret.STRAVA_TOKEN_ENDPOINT |b64enc }}
  NON_VOLATILE_STORAGE_DIR: {{ .Values.secret.NON_VOLATILE_STORAGE_DIR |b64enc }}
  GOOGLE_SHEETS_SHEET_ID: {{ .Values.secret.GOOGLE_SHEETS_SHEET_ID |b64enc }}
  GOOGLE_CLOUD_CREDENTIALS_PATH: {{ .Values.secret.GOOGLE_CLOUD_CREDENTIALS_PATH |b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: google-cloud-token
  labels:
    app: {{ template "miles-challenge.name" . }}
    chart: {{ template "miles-challenge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  google-cloud-credentials.json: |-
    {{ .Values.secret.GOOGLE_CLOUD_CREDENTIALS_JSON | b64enc }}
